/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.schneezey.pojo;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TEST_ENUM {
  TYPEA, TYPEB, TYPEC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TEST_ENUM\",\"namespace\":\"io.schneezey.pojo\",\"symbols\":[\"TYPEA\",\"TYPEB\",\"TYPEC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
